/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//ADC1
//PA1
#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"


void pa1_adc_init(void);
uint32_t adc_read(void);
void adc_start_converstion(void);
void adc_read_pin(void);






//#define ADC1EN      (1U<<8)
//#define ADC_CH1      (1U<<0)
//#define ADC_SEQ_LEN_1   0x00
//#define CR2_AD0N    (1U<<0)
//#define CR2_SWSTART    (1U<<30)
//#define SR_EOC      (1U<<1)
//#define CR2_CONT    (1U<<1)



uint32_t adc_read_value;



void pa1_adc_init(void)
{
	RCC->AHB1ENR |= (1 << 0);
	GPIOA->MODER |=(1U<<2);
	GPIOA->MODER |=(1U<<3);
	RCC->APB2ENR |= (1<<8);//ADC1EN
	ADC1->SQR3 = (1 <<0);//ADC_CH1
	ADC1->SQR1 = 0x00;//ADC_SEQ_LEN_1
	ADC1->CR2 |= (1 << 0);//CR2_AD0N
}





void adc_start_converstion(void)
{
	ADC1->CR2 |= (1 << 1);//CR2_CONT
	ADC1->CR2 |= (1 << 30);//CR2_SWSTART
}

uint32_t adc_read(void)
{
	while(!(ADC1->SR & (1 << 1))){}//SR_EOC
	return (ADC1->DR);
}



void adc_read_pin(void )
{
	adc_read_value =  adc_read();
	printf("ADC is ACTIVE in PA1\n\r");
	printf("ADC reading : %d \n\r",(int)adc_read_value);
}



int main(void)
{
	pa1_adc_init();
	adc_start_converstion();
	while(1)
	{
		adc_read_pin();
	}
}
